# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"main": "00_core.ipynb",
         "init_parameters_from_settings": "00_core.ipynb",
         "build": "00_core.ipynb",
         "build_question": "00_core.ipynb",
         "join": "01_tex.ipynb",
         "gaussian_pdf": "01_tex.ipynb",
         "q_function_approximation": "01_tex.ipynb",
         "partwise_function": "01_tex.ipynb",
         "from_number": "01_tex.ipynb",
         "from_matrix": "01_tex.ipynb",
         "dot_product": "01_tex.ipynb",
         "total_probability": "01_tex.ipynb",
         "enumerate_math": "01_tex.ipynb",
         "enumerate_assignments": "01_tex.ipynb",
         "expand": "01_tex.ipynb",
         "render_latex": "02_util.ipynb",
         "to_formula_maybe": "02_util.ipynb",
         "AccessorEndowedClass": "02_util.ipynb",
         "int_to_roman": "02_util.ipynb",
         "dict_to_yaml": "02_util.ipynb",
         "yaml_to_dict": "02_util.ipynb",
         "write_multiple_categories": "02_util.ipynb",
         "supplement_file_name": "02_util.ipynb",
         "add_name": "02_util.ipynb",
         "markdown_from_question": "02_util.ipynb",
         "generator_to_markdown": "02_util.ipynb",
         "latex_to_markdown": "02_util.ipynb",
         "wrong_numerical_solutions_from_correct_one": "02_util.ipynb",
         "pre_process_string_template": "03_question.ipynb",
         "QuestionGenerator": "03_question.ipynb",
         "NumericalQuestionGenerator": "03_question.ipynb",
         "MultipleChoiceQuestionGenerator": "03_question.ipynb",
         "MultipleChoiceTheoreticalQuestionGenerator": "03_question.ipynb",
         "extract_class_settings": "40_input_file.ipynb",
         "Settings": "40_input_file.ipynb",
         "initialize": "40_input_file.ipynb",
         "set_class_preamble": "40_input_file.ipynb",
         "set_class_closing": "40_input_file.ipynb",
         "set_class": "40_input_file.ipynb",
         "write_header": "40_input_file.ipynb",
         "write_class_preamble": "40_input_file.ipynb",
         "write_class_closing": "40_input_file.ipynb",
         "function_to_make_hierarchical_category_name": "40_input_file.ipynb",
         "TimeKeeper": "50_time.ipynb",
         "ClassesContainer": "60_notebook.ipynb",
         "MyMagics": "60_notebook.ipynb",
         "matrix": "70_hash.ipynb",
         "number": "70_hash.ipynb",
         "string": "70_hash.ipynb"}

modules = ["core.py",
           "tex.py",
           "util.py",
           "question.py",
           "input_file.py",
           "time.py",
           "notebook.py",
           "hash.py"]

doc_url = "https://manuvazquez.github.io/py2gift/"

git_url = "https://github.com/manuvazquez/py2gift/tree/master/"

def custom_doc_links(name): return None
