# AUTOGENERATED! DO NOT EDIT! File to edit: 70_hash.ipynb (unless otherwise specified).

__all__ = ['matrix', 'number', 'string']

# Cell
from typing import Union, Optional

import numpy as np

# Cell
def matrix(matrix: Union[list, np.ndarray], decimal_sep_replacement: Optional[bool] = '_') -> str:

    res = ''.join(np.vectorize(str)(np.array(matrix).flatten()))

    if decimal_sep_replacement:

        res = res.replace(r'.', decimal_sep_replacement)

    return res

assert matrix([2, 3]) == '23'

# Cell

def number(number: Union[float, np.float64], decimal_sep_replacement: Optional[bool] = '_') -> str:

    res = str(number)

    if decimal_sep_replacement:

        res = res.replace(r'.', decimal_sep_replacement)

    return res

assert number(2.3) == '2_3'

# Cell

def string(s: str) -> str:

    return ''.join(x for x in s if x.isalnum())