# AUTOGENERATED! DO NOT EDIT! File to edit: 01_tex.ipynb (unless otherwise specified).

__all__ = ['gaussian_pdf', 'q_function_approximation']

# Cell
from typing import Union, Iterable

import numpy as np

from .util import to_formula_maybe

# Cell
@to_formula_maybe
def gaussian_pdf(x: str = 'x', mean: str = r'\mu', variance: str = r'\sigma^2') -> str:
    """
        Returns a string representing the probability density function for a Gaussian distribution.
    """

    return r'\frac{1}{\sqrt{2\pi ' + variance + r'}}e^{-\frac{(' + x + '-' + mean + r')^2}{2' + variance + r'}}'

# Cell
@to_formula_maybe
def q_function_approximation(x: str = 'x') -> str:
    """
    Returns a string representing the Stirling approximation.
    """

    return f'Q({x}) \\approx \\frac{{1}}{{2}} e^{{-\\frac{{{x}^2}}{{2}}}}'