# AUTOGENERATED! DO NOT EDIT! File to edit: 50_time.ipynb (unless otherwise specified).

__all__ = ['accumulator_field', 'TimeKeeper']

# Cell
from typing import Union

import pandas as pd

# Cell

accumulator_field = 'acc_time'

# Cell

class TimeKeeper:

    def __init__(self) -> None:

        self.category_time_df = pd.DataFrame(columns=['category', 'time'])

    def record(self, minutes: int, category_name: Union[str, list]) -> None:


        category_name = category_name if type(category_name)==str else category_name[-1]
        self.category_time_df = self.category_time_df.append({'category': category_name, 'time': minutes}, ignore_index=True)

    def __str__(self) -> str:

        return f'Accumulated time: {self.category_time_df["time"].sum()} minutes'