# AUTOGENERATED! DO NOT EDIT! File to edit: 02_util.ipynb (unless otherwise specified).

__all__ = ['render_latex', 'to_formula_maybe']

# Cell
import IPython.display

# Cell
def render_latex(formula: str) -> str:

    assert formula[0] == '$'

    return IPython.display.Markdown(r'$\Large' + formula[1:])

# Cell
def to_formula_maybe(func):

    def wrapper(*args, **kwargs):

        if ('to_formula' in kwargs) and (kwargs['to_formula']):

            kwargs.pop('to_formula')

            return f'${func(*args, **kwargs)}$'

        else:

            return func(*args, **kwargs)
    return wrapper